[package]
name = "objviewer"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
color-eyre = "0.6.3"
glam = "0.30.2"
glow = "0.16.0"
sdl3 = { version = "0.14.25", features = ["use-vcpkg"] }
wavefront = "0.2.3"
